# Copyright (c) 2023-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

stages:          # List of stages for jobs, and their order of execution
  - build
  - release

# Define what triggers a pipeline, to prevent duplicate pipelines from running
# [Documentation](https://docs.gitlab.com/ee/ci/jobs/job_control.html#avoid-duplicate-pipelines)
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^\[\s*[Ss][Kk][Ii][Pp]([_\-]|\s*)[Cc][Ii]\s*\].*/
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always # Trigger Pipeline Creation when running a scheduled CI job
    - if: $CI_SKIP == "true"
      when: never # Allow Skipping CI with environment variable. Pipeline must still pass before MR is able to be merged!
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never # Do not trigger CI pipelines on push events outside of a "merge_request_event"
    - when: always


variables:
  NGINX_IMAGE_NAME: nvcr.io/nvidian/kaze/container-cache
  NGINX_IMAGE_TAG: $CI_COMMIT_TAG
  CERT_WATCHER_IMAGE_NAME: nvcr.io/nvidian/kaze/container-cache-cert-watcher
  CERT_WATCHER_IMAGE_TAG: $CI_COMMIT_TAG
  COMPONENT_NAME: container-cache

build-image:
  stage: build
  tags: ["build"]
  script:
    - echo $NGC_API_KEY | docker login -u "\$oauthtoken" nvcr.io --password-stdin
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t ${CI_REGISTRY_IMAGE}/nginx:${CI_PIPELINE_ID}  -f Dockerfile.containerd .
    - docker push  ${CI_REGISTRY_IMAGE}/nginx:${CI_PIPELINE_ID}
    - cd gfn/cert-watcher
    - docker build -t ${CI_REGISTRY_IMAGE}/cert-watcher:${CI_PIPELINE_ID} -f Dockerfile.containerd .
    - docker push ${CI_REGISTRY_IMAGE}/cert-watcher:${CI_PIPELINE_ID}
release-nginx-image:
  stage: release
  tags: ["build"]
  rules:
    - if: $CI_COMMIT_TAG # Runs when a tag is created
  script:
    - echo $NGC_API_KEY | docker login -u "\$oauthtoken" nvcr.io --password-stdin
    - docker build -t ${NGINX_IMAGE_NAME}:${NGINX_IMAGE_TAG} -f Dockerfile.containerd .
    - docker push ${NGINX_IMAGE_NAME}:${NGINX_IMAGE_TAG}

release-cert-update:
  stage: release
  tags: ["build"]
  rules:
    - if: $CI_COMMIT_TAG # Runs when a tag is created
  script:
    - cd gfn/cert-watcher
    - echo $NGC_API_KEY | docker login -u "\$oauthtoken" nvcr.io --password-stdin
    - docker build -t ${CERT_WATCHER_IMAGE_NAME}:${CERT_WATCHER_IMAGE_TAG} -f Dockerfile.containerd .
    - docker push ${CERT_WATCHER_IMAGE_NAME}:${CERT_WATCHER_IMAGE_TAG}
