# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: remove-containerd-configuration
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: remove-containerd-configuration
  template:
    metadata:
      labels:
        name: remove-containerd-configuration
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      initContainers:
      - name: remove-configuration
        image: nvcr.io/nvidia/cuda:12.3.2-base-ubuntu22.04
        env:
        - name: TARGET_HOST
          value: "nvcr.io"
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-containerd
          mountPath: /host/etc/containerd
        command: ["/bin/bash"]
        args:
        - -c
        - |
          rm -rf /host/etc/containerd/certs.d/${TARGET_HOST}
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
      volumes:
      - name: etc-containerd
        hostPath:
          path: /etc/containerd
