# Copyright (c) 2023-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# Number of replicas to create of Container Cache.
replicaCount: 1

# Domain of target Host where the proxy passes the request to (default: nvcr.io).
targetHost: stg.nvcr.io

# Container image information used by Container Cache.
images:
  # Name of the container image containing Container Cache Nginx Proxy.
  server: nvcr.io/nvstaging/clara-internal/supare:nvcf_cache53

  # Name of the container image containing Nginx Prometheus Exporter.
  exporter: nginx/nginx-prometheus-exporter:1.0

  # Name of Kubernetes secrets used to pull container image during pod deployment.
  secrets:
    # The name of the Kubernetes secret to be used (NOT the secret itself).
    - ngc-container-pull

# Configuration options related to how Container Cache is configured.
cache:
  # Size for storing cache keys (default: 10m).
  # Must be a positive integer and followed by a scale suffix of k or K (kilobytes), m or M (megabytes), g or G (gigabytes).
  keyStorageSize: 10m

  # Max size of the cache (default: 80g).
  # Must be a positive integer and followed by a scale suffix of k or K (kilobytes), m or M (megabytes), g or G (gigabytes).
  maxSize: 180g

  # Period a resource can remain in the cache without being accessed (default: 60d).
  # Must be a positive integer and followed by a scale suffix from https://nginx.org/en/docs/syntax.html.
  inactive: 60d

  # Period a cache is valid if the resource doesn't become inactive first (default: 60d).
  # Must be a positive integer and followed by a scale suffix from https://nginx.org/en/docs/syntax.html.
  valid: 60d

# Configuration options related to how Container Cache Persistent Volume Claim is configured.
pvc:
  # Size of persistent volume claim (default: 100Gi )
  size: 200Gi

# Configuration options related to how Container Cache Service is configured.
service:
  # Type of Kubernetes service connection used by the server to provide network API services (default: ClusterIP).
  # Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer.
  type: NodePort

  # Port to use to connect to the Container Cache Service (default: 30345).
  port: 30345

# Configuration options related to how Container Cache Metrics are configured.
metrics:
  # Size for storing cache Metrics (default: 10m).
  # Must be a positive integer and followed by a scale suffix of k or K (kilobytes), m or M (megabytes), g or G (gigabytes).
  cacheMetricsStorageSize: 10m

# Custom annotations to be added to the pod.
podAnnotations: {}

# Custom labels to be added to the pod.
podLabels: {}
