# Use ARGs to define versions
# ARG NGINX_VERSION=1.21.4
ARG OPENRESTY_VERSION=openresty-1.21.4.3
ARG PATCH_FILE=proxy_connect_rewrite_102101.patch

FROM ubuntu:latest

# Re-define ARGs inside the build stage
ARG OPENRESTY_VERSION
ARG PATCH_FILE

# Avoid APT warnings
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt update && \
	apt upgrade -y && \
    apt install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev wget git luarocks

# Add nginx user
RUN useradd -r -m -d /var/cache/nginx -s /sbin/nologin nginx

# Set working directory
WORKDIR /usr/src

# Clone ngx_http_proxy_connect_module
RUN git clone https://github.com/chobits/ngx_http_proxy_connect_module.git

# Download and extract OpenResty
RUN wget https://openresty.org/download/${OPENRESTY_VERSION}.tar.gz && \
    tar -zxvf ${OPENRESTY_VERSION}.tar.gz

# Download the raw patch file
RUN wget https://raw.githubusercontent.com/chobits/ngx_http_proxy_connect_module/master/patch/${PATCH_FILE} -O ${PATCH_FILE}

# Custom NGINX configuration

ARG NGINX_CONFIG="\
	# User and group settings
		--user=nginx \
		--group=nginx \
		--prefix=/etc/nginx \
		--sbin-path=/usr/sbin/nginx \
		--modules-path=/usr/lib/nginx/modules \
		--conf-path=/etc/nginx/nginx.conf \
		--error-log-path=/var/log/nginx/error.log \
		--http-log-path=/var/log/nginx/access.log \
		--pid-path=/var/run/nginx.pid \
		--lock-path=/var/run/nginx.lock \
	# Temporary path settings
		--http-client-body-temp-path=/var/cache/nginx/client_temp \
		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
		--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
		--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
	# Modules configuration
		--with-compat \
		--with-file-aio \
		--with-http_addition_module \
		--with-http_auth_request_module \
		--with-http_gunzip_module \
		--with-http_gzip_static_module \
		--with-http_random_index_module \
		--with-http_realip_module \
		--with-http_secure_link_module \
		--with-http_slice_module \
		--with-http_ssl_module \
		--with-http_stub_status_module \
		--with-http_sub_module \
		--with-http_v2_module \
		--with-threads \
		--with-stream \
		--with-stream_realip_module \
		--with-stream_ssl_module \
		--with-stream_ssl_preread_module \
	"
# Compile and install OpenResty
WORKDIR ${OPENRESTY_VERSION}
RUN ./configure --add-module=/usr/src/ngx_http_proxy_connect_module ${NGINX_CONFIG} && \
   patch -d build/nginx-1.21.4/ -p 1 < /usr/src/${PATCH_FILE} && \
   make && make install \
   && ln -sf /dev/stdout /var/log/nginx/access.log \
   && ln -sf /dev/stderr /var/log/nginx/error.log

# Add needed Lua modules
RUN luarocks install lua-resty-http && luarocks install lua-resty-core

# Clean up build directory
RUN rm -rf /tmp/*

# Run from the root directory (unset initial change to root directory)
WORKDIR /

# Sanity check of binary and default nginx.conf
RUN nginx -v && nginx -t

# Define default command
CMD ["nginx", "-g", "daemon off;"]
