apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: NVCF added ca-certificates bundle
  name: nvcf-cert-bundle-cm
  namespace: container-caching
data:
  ca-certificates.crt: |
{{ $.Values.nvcfRootCert | indent 4 }}
{{ $.Values.caRoot | indent 4 }}

  cert.pem: |
{{ $.Values.nvcfRootCert | indent 4 }}
{{ $.Values.caRoot | indent 4 }}

  NVIDIA_Root_CA_1.crt: |
{{ $.Values.nvcfRootCert | indent 4 }}

  {{ $.Values.nvcfRootCertHash }}: |
{{ $.Values.nvcfRootCert | indent 4 }}


