# Copyright (c) 2023-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: v1
kind: ConfigMap
metadata:
  name: nvcf-proxy-config
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ $.Release.Name }}
    {{- include "nvcf-container-cache.labels" . | nindent 4 }}
data:
  proxy-cache.conf: |-
     {{ tpl (.Files.Get "files/proxy-cache.conf") . | nindent 4 }}
  proxy-nucleus-cache.conf: |-
     {{ tpl (.Files.Get "files/proxy-nucleus-cache.conf") . | nindent 4 }}
  ngc.conf: |-
     {{ tpl (.Files.Get "files/ngc.conf") . | nindent 4 }}
  hf.conf: |-
     {{ tpl (.Files.Get "files/hf.conf") . | nindent 4 }}
  proxy-common.conf: |-
     {{ tpl (.Files.Get "files/proxy-common.conf") . | nindent 4 }}
