# Copyright (c) 2023-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $.Release.Name }}-cc
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ $.Release.Name }}
    {{ include "nvcf-container-cache.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: configure-containerd
  template:
    metadata:
      labels:
        name: configure-containerd
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
    {{- with $.Values.images.secrets }}
      imagePullSecrets:
    {{- range $idx, $item := . }}
        - name: {{ $item }}
    {{- end }}
    {{- end }}
      containers:
      - name: configure
        image: {{ $.Values.images.certificates }}
        env:
        - name: TARGET_HOST
          value: {{ $.Values.targetHost | default "nvcr.io" | quote }}
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: VAULT_ENABLED
          value: {{ $.Values.vault.enabled | default false | quote }}
        - name: CERT_LOCATION
          value: {{ $.Values.vault.certLocation | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-containerd
          mountPath: /host/etc/containerd
        - name: ssl-certs
          mountPath: /host/etc/ssl/
        command: ["/bin/bash"]
        args:
        - -c
        - |
          hosts=(${TARGET_HOST//,/ })
          rm -rf /host/etc/containerd/certs.d/*
          for host in "${hosts[@]}"; do
          echo "$host"
          mkdir -p /host/etc/containerd/certs.d/$host
          cat <<EOF >/host/etc/containerd/certs.d/$host/hosts.toml
              server = "https://$host"
              [host."https://${NODE_IP}:{{ $.Values.service.port }}"]
              capabilities = ["pull", "resolve"]
              ca = "/etc/ssl/nginx_container_cache.crt"
          EOF
          done
          if [ "${VAULT_ENABLED}" = "true" ]; then
            curl ${CERT_LOCATION} -o  /host/etc/ssl/nginx_container_cache.crt
          else
            cp /ca/root.crt.pem /host/etc/ssl/nginx_container_cache.crt
          fi
          python3 update_config.py /host/etc/containerd/config.toml
          while true; do sleep 1000; done
      volumes:
      - name: etc-containerd
        hostPath:
          path: /etc/containerd
      - name: ssl-certs
        hostPath:
          path: /etc/ssl
