# Copyright (c) 2023-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: v1
kind: Service
metadata:
  name: lft-nvcf-proxy-cache
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: lft-nvcf-proxy-cache
    {{- include "nvcf-container-cache.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https-nucleus
      name: https-nucleus
      protocol: TCP
  selector:
    {{- include "nvcf-container-cache.selectorLabels" . | nindent 4 }}
