# Copyright (c) 2023-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ $.Release.Name }}
    {{- include "nvcf-container-cache.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "nvcf-container-cache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-status: update
        vault.hashicorp.com/agent-configmap: {{ $.Release.Name }}-vault-config
        vault.hashicorp.com/secret-volume-path: "/vault/secrets"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nvcf-container-cache.labels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
    {{- end }}
      initContainers:
      - command:
        - chown
        - -R
        - 1000:1000
        - /container_cache
        image: nvcr.io/nvidia/cuda:12.3.2-base-ubuntu22.04
        name: init-chown-data
        resources: {}
        volumeMounts:
        - name: cache
          mountPath: /container_cache
        securityContext:
          capabilities:
              add:
              - CHOWN
          runAsNonRoot: false
          runAsUser: 0
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccountName: container-cache
    {{- with $.Values.images.secrets }}
      imagePullSecrets:
    {{- range $idx, $item := . }}
      - name: {{ $item }}
    {{- end }}
    {{- end }}
      containers:
        - name: nginx-proxy
          image: {{ required "Property '.images.server' is required." $.Values.images.server | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 13129
              protocol: TCP
            - name: https
              containerPort: 13128
              protocol: TCP
            - name: cache-metrics
              containerPort: 9145
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: cache
              mountPath: /container_cache
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount-vault
        - name: nginx-prometheus-exporter
          image: {{ required "Property '.images.exporter' is required." $.Values.images.exporter | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - '-nginx.scrape-uri=http://localhost:9145/nginx_status'
          ports:
            - name: metrics
              containerPort: 9113
      volumes:
        - name: token
          projected:
            sources:
            - serviceAccountToken:
                path: token
                audience: https://stg.vault.nvidia.com
        - name: nginx-config
          configMap: 
            name: {{ $.Release.Name }}-config
  volumeClaimTemplates:
    - metadata:
        name: cache
        namespace: {{ $.Release.Namespace | quote }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.persistentVolumeClaim.size | default "100Gi" | quote }}
        storageClassName: {{ $.Values.persistentVolumeClaim.storageClassName | default "azurefile" | quote }}
