# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG TAG=v3.0.6
ARG IMG=nvcr.io/nvidian/distroless/go
FROM golang:1.19 as builder

ENV DEBIAN_FRONTEND=noninteractive

ENV CGO_ENABLED=0

WORKDIR /app

COPY . .

# build our go executable
RUN go build

FROM $IMG:$TAG

# Copy the go executable into our final container
COPY --from=builder /app/cert-watcher /app/cert-watcher

CMD ["/app/cert-watcher"]
