    # The caching layer
    server {
        set $docker_proxy_request_type "nvcf-proxy-cache";
        include  /etc/nginx/conf.d/sites/proxy-common.conf;
        access_log /dev/stdout main buffer=256k flush=10s;

        # Listen on 14128, for all hostnames.
        listen 14128 ssl;
        # override specific configurations from proxy-common.conf
        http2 on;
        server_name huggingface.co;
        proxy_cache_lock_timeout 30s;
        proxy_cache_lock_age 100s;
        proxy_cache proxy_ngc;

        set_by_lua_block $ssl_server_name {
          local headers = ngx.req.get_headers()
          return headers["Host"]
        }

        location  / {
          proxy_pass_request_headers on;
          proxy_set_header Range $http_range;
          proxy_cache_key $request_method|$uri|$arg_versionId|$http_range;
          access_by_lua_file /etc/nginx/conf.d/lua/lua-access.lua;
          proxy_set_header Host $host;
          proxy_pass $scheme://$host;
        }
    }
