    # The caching layer
    server {

        include  /etc/nginx/conf.d/sites/proxy-common.conf;

        # Listen on 14128, for all hostnames.
        listen 14128 ssl;
        http2 on;
        keepalive_requests 1000;
        server_name xfiles.stg.ngc.nvidia.com files.ngc.nvidia.com;
        proxy_cache_lock_timeout 30s;
        proxy_cache_lock_age 100s;

        set_by_lua_block $ssl_server_name {
          local headers = ngx.req.get_headers()
          return headers["Host"]
        }

        location  / {
          proxy_pass_request_headers on;
          proxy_set_header Range $http_range;
          proxy_cache_key $request_method|$uri|$arg_versionId|$http_range;
          access_by_lua_file /etc/nginx/conf.d/lua/lua-access.lua;
          proxy_set_header Host $host;
          proxy_pass $scheme://$host;
        }
    }
