receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: {{ .Values.traces.collector.endpoint | quote }}
    headers:
      "lightstep-access-token": ${env:OTEL_COLLECTOR_ACCESS_TOKEN}

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]