# Copyright (c) 2023-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# Sepcify labels for selecting node.
nodeSelector:
  node.kubernetes.io/instance-type: Standard_D64s_v3

# Number of replicas to create of Container Cache.
replicaCount: 1

# Domain of target Host where the proxy passes the request to (default: nvcr.io).
targetHost: stg.nvcr.io,nvcr.io,ghcr.io

# Container image information used by Container Cache.
images:
  # Name of the container image containing Container Cache Nginx Proxy.
  #server: nvcr.io/qtfpt1h0bieu/nvcf-core/nvcf-container-cache:v1.0
  server: stg.nvcr.io/nv-cf/nvcf-core/nvcf-container-cache:v1.1.25

  # Name of the container image containing Nginx Prometheus Exporter.
  exporter: nginx/nginx-prometheus-exporter:1.0

  # Name of Kubernetes secrets used to pull container image during pod deployment.
  secrets:
    # The name of the Kubernetes secret to be used (NOT the secret itself).
    - balaji-cred

# Configuration options related to how Container Cache is configured.
cache:
  # Size for storing cache keys (default: 10m).
  # Must be a positive integer and followed by a scale suffix of k or K (kilobytes), m or M (megabytes), g or G (gigabytes).
  keyStorageSize: 50m

  # Max size of the cache (default: 80g).
  # Must be a positive integer and followed by a scale suffix of k or K (kilobytes), m or M (megabytes), g or G (gigabytes).
  maxSize: 180g

  # Period a resource can remain in the cache without being accessed (default: 60d).
  # Must be a positive integer and followed by a scale suffix from https://nginx.org/en/docs/syntax.html.
  inactive: 1d

  # Period a cache is valid if the resource doesn't become inactive first (default: 60d).
  # Must be a positive integer and followed by a scale suffix from https://nginx.org/en/docs/syntax.html.
  valid: 1h


# Configuration options related to how Container Cache Persistent Volume is configured.
persistentVolumeClaim:
  # Size of persistent volume (default: 100Gi )
  sizeGB: 100

  # Name of storage class for persistent volume claim (default: azurefile )
  storageClassName: azurefile

  # Size of persistent volume for proxy cache (in GB, default 100)
  sizeProxyGB: 100
  # Percentage of space to keep free in proxyCache persistent volume to not trigger alarms
  # WARNING: changing this value out of the default may trigger proxy cache disk space alerts for the cluster. Ensure
  # those are adjusted beforehand.
  # freeProxyPct: 5

# Configuration options related to how Container Cache Service is configured.
service:
  # Type of Kubernetes service connection used by the server to provide network API services (default: ClusterIP).
  # Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer.
  type: NodePort

  # Port to use to connect to the Container Cache Service (default: 30345).
  port: 30345

# Configuration options related to how Container Cache Metrics are configured.
metrics:
  # Size for storing cache Metrics (default: 10m).
  # Must be a positive integer and followed by a scale suffix of k or K (kilobytes), m or M (megabytes), g or G (gigabytes).
  cacheMetricsStorageSize: 300m

  # Bucket configuration for the throughput histogram (default: 25000000, 30000000, 35000000, 40000000, 50000000, 60000000, 80000000, 100000000).
  # Must be a comma-separated list of positive integers.
  throughputHistogramBuckets: 25000000, 30000000, 35000000, 40000000, 50000000, 60000000, 80000000, 100000000

# Custom annotations to be added to the pod.
podAnnotations: {}

# Custom labels to be added to the pod.
podLabels: {}

# Vault configuration.
vault:
  # Cluster Cloud Service Provider (default: azure).
  clusterCSP: azure

  # Cluster Region (default: scus).
  clusterRegion: scus

  # Cluster Account Name (default: sis-azure-stage).
  clusterAccountName: sis-azure-stage

  # Cluster Name (default: stage).
  clusterName: getty

  # Vault Address (default: https://stg.vault.nvidia.com:443).
  vaultAddress: https://stg.vault.nvidia.com


nvcfRootCert: |
  -----BEGIN CERTIFICATE-----
  MIIGpTCCBI2gAwIBAgIUWoUMzmHB4HpEgAZ5DvsoLVWgnP4wDQYJKoZIhvcNAQEL
  BQAwgYYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRQwEgYDVQQH
  EwtTYW50YSBDbGFyYTEbMBkGA1UEChMSTlZJRElBIENvcnBvcmF0aW9uMQ0wCwYD
  VQQLEwROVkNGMSAwHgYDVQQDExdOVkNGIFN0YWdpbmcgUm9vdCBDQSAwMTAeFw0y
  MzExMTMxODI0MjBaFw00ODExMDYxODI0NDlaMIGGMQswCQYDVQQGEwJVUzETMBEG
  A1UECBMKQ2FsaWZvcm5pYTEUMBIGA1UEBxMLU2FudGEgQ2xhcmExGzAZBgNVBAoT
  Ek5WSURJQSBDb3Jwb3JhdGlvbjENMAsGA1UECxMETlZDRjEgMB4GA1UEAxMXTlZD
  RiBTdGFnaW5nIFJvb3QgQ0EgMDEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
  AoICAQCVR3ACa3GX5DMum+Dwx840CHmdXfRXvbkOt33I7JBBVgG4uwzRvHA54qtP
  s5qRXFxAyNgG8FIWnHQIiGNLxZ1Zaufrbz8ejCUp0EUSPy/y5UKQb8XMuP4eVquF
  s5PYrernoyU8tuxiaGaWjSeH8ctILocequ39GOe1fIdX/9cuRczoRoueaeE0bkkk
  sL5UbnBdO42y5OJwGNHLx+a6Tf88DSrbriW/5OPaBcGPnw3B01Dqzlnq/of1A2aj
  Wzvbym/SG+AP6F+/zuUdXKuNAElH8/030Bo3B1e5lx7sNJztBDMUdUE3CwHoUkZc
  XttTBX6yIBD4nKuXyjvhUgf06FjAUxOgUypcQ8wTd/tQie9XWHe7VsUwXMyBxRz+
  1QNf5kepGF/SpzUbDJsFoBCpVVr62vCtXuteJvwXtFUf0jiDVeHK/rMBGc91ASPI
  +KtvU0jZM/rW5jEDnt9RG5jQNwYly9f7NddykNrMdUkEYi04F8ye5mAGmqOsPStc
  tb0HBeB9vqYGKp6Rh50Df0kqBoHmknhH4s9Inp2cDkku+las1aLaBEjTHoqI7aSA
  /FbsZxGVH5wxibUfgqz5OviF3vCzGM5LUsV18mPzOKCptHQgMyJa6T747DYP2kKW
  /wTAqV24ETWxv9juqvNk4h1Tmuas0uCL69vsRlNa4+wpU/Q6CwIDAQABo4IBBzCC
  AQMwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFFB5
  twikAIfR+s/6wsu9xWAGeRdLMB8GA1UdIwQYMBaAFFB5twikAIfR+s/6wsu9xWAG
  eRdLMFQGCCsGAQUFBwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL2NybHMtc3Rn
  LnZwa2kubnZpZGlhLmNvbS9oaXMzL210azNuMmk1bnRrMnl0am0vY2EwSgYDVR0f
  BEMwQTA/oD2gO4Y5aHR0cDovL2NybHMtc3RnLnZwa2kubnZpZGlhLmNvbS9oaXMz
  L210azNuMmk1bnRrMnl0am0vY3JsMA0GCSqGSIb3DQEBCwUAA4ICAQAoOmzUBfwh
  k8kzxU/KkanBFoqWm3YdEjQvHmjXUaGwP6XPQcOiMeX2hVWoV4ij9yt4hgoGrwj8
  +Q4WhCOGJnDzNhTbtS/Fg4qDOw5Wl/WwzFxYwAzj3GXzL7fZJZtc5INwRPKNpTJM
  861b89ZQBDFx0UC3CSxhQRvzUQnDkzAds1pq36OANI08WZLkUEwE8J5dLHZGGD+i
  HvGCTDGLuxWidhft5WtzJ4HQqVz9L0JwjzqQ1W/cBkClEUcZccLq5g8Kmmnmbk4e
  AkaazE2iWVoKV5A3akt2OXQKIOhhugDAzJoV1n9V63/KlusZHsNqElSZ57QLszIJ
  Uk/duvyrPiojVb9bp4K2UlFKxNxjoGSu2rUfV/LicASqyTTH/HSYWGSveLOVo690
  OgMyNKkAuBt5i5Fxu8UX9UR/7Z20z3RYlVvMVF9K3V7ReU9yrKCZ+60rJk24RFcq
  q1k+9MTcHsMDInPl0OpmSRtOQvpkC67IuFc7ROOzLBWgHC0W70aasv5thkfmj2rh
  L+pVCgVjEeYGjWQqA1IK/f6LoKKEf0TzPOy/Osh9Nsvp0Y4I4ZytNfb5EIfKYpnA
  SsWF6UQxTi65lbra6hjuwlCeZyZP4a071XgXVmOi53yXjGWJ3Bw80binfRZOnmrj
  4Rc6Yt9uF7Uc3G0CtrxDJNHh9NjgEn8BcQ==
  -----END CERTIFICATE-----
