apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-container-cache
  labels:
    app: nginx-container-cache
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: nginx-container-cache
  template:
    metadata:
      labels:
        app: nginx-container-cache
    spec:
      containers:
      - name: nginx
        image: container-cache:latest # Replace with your Docker image
        ports:
        - containerPort: 443
        # If you need to mount configuration or certificates from a ConfigMap or Secret:
        # volumeMounts:
        # - name: config-volume
        #   mountPath: /etc/nginx/conf.d
        # volumes:
        # - name: config-volume
        #   configMap:
        #     name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-container-cache-service
spec:
  selector:
    app: nginx-container-cache
  ports:
    - protocol: TCP
      port: 13128
      targetPort: 13128
  type: ClusterIP 
