apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Chart.Name }}-pvc
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ $.Release.Name }}
    {{- include "nvcf-container-cache.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi